// Code generated by "stringer -trimprefix=Difficulty -type=Difficulty"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DifficultyPeaceful-0]
	_ = x[DifficultyEasy-1]
	_ = x[DifficultyNormal-2]
	_ = x[DifficultyHard-3]
}

const _Difficulty_name = "PeacefulEasyNormalHard"

var _Difficulty_index = [...]uint8{0, 8, 12, 18, 22}

func (i Difficulty) String() string {
	if i < 0 || i >= Difficulty(len(_Difficulty_index)-1) {
		return "Difficulty(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Difficulty_name[_Difficulty_index[i]:_Difficulty_index[i+1]]
}
