package game

import "github.com/tsatke/nbt"

var codec = nbt.NewCompoundTag("", []nbt.Tag{
	nbt.NewCompoundTag("minecraft:dimension_type", []nbt.Tag{
		nbt.NewStringTag("type", "minecraft:dimension_type"),
		nbt.NewListTag("value", []nbt.Tag{
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:overworld"),
				nbt.NewIntTag("id", 0),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewByteTag("ultrawarm", 0),
					nbt.NewByteTag("has_ceiling", 0),
					nbt.NewFloatTag("ambient_light", 0),
					nbt.NewByteTag("respawn_anchor_works", 0),
					nbt.NewByteTag("has_skylight", 1),
					nbt.NewByteTag("bed_works", 1),
					nbt.NewStringTag("effects", "minecraft:overworld"),
					nbt.NewByteTag("has_raids", 1),
					nbt.NewIntTag("logical_height", 256),
					nbt.NewDoubleTag("coordinate_scale", 1),
					nbt.NewByteTag("piglin_safe", 0),
					nbt.NewByteTag("natural", 1),
					nbt.NewStringTag("infiniburn", "minecraft:infiniburn_overworld"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:overworld_caves"),
				nbt.NewIntTag("id", 1),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewByteTag("has_skylight", 1),
					nbt.NewByteTag("bed_works", 1),
					nbt.NewByteTag("has_raids", 1),
					nbt.NewIntTag("logical_height", 256),
					nbt.NewByteTag("piglin_safe", 0),
					nbt.NewByteTag("natural", 1),
					nbt.NewFloatTag("ambient_light", 0),
					nbt.NewByteTag("respawn_anchor_works", 0),
					nbt.NewByteTag("has_ceiling", 1),
					nbt.NewStringTag("infiniburn", "minecraft:infiniburn_overworld"),
					nbt.NewStringTag("effects", "minecraft:overworld"),
					nbt.NewDoubleTag("coordinate_scale", 1),
					nbt.NewByteTag("ultrawarm", 0),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:the_nether"),
				nbt.NewIntTag("id", 2),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("coordinate_scale", 8),
					nbt.NewByteTag("natural", 0),
					nbt.NewStringTag("effects", "minecraft:the_nether"),
					nbt.NewByteTag("has_raids", 0),
					nbt.NewStringTag("infiniburn", "minecraft:infiniburn_nether"),
					nbt.NewIntTag("fixed_time", 18000),
					nbt.NewByteTag("has_ceiling", 1),
					nbt.NewIntTag("logical_height", 128),
					nbt.NewByteTag("ultrawarm", 1),
					nbt.NewFloatTag("ambient_light", 0.1),
					nbt.NewByteTag("respawn_anchor_works", 1),
					nbt.NewByteTag("has_skylight", 0),
					nbt.NewByteTag("piglin_safe", 1),
					nbt.NewByteTag("bed_works", 0),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:the_end"),
				nbt.NewIntTag("id", 3),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewByteTag("natural", 0),
					nbt.NewStringTag("infiniburn", "minecraft:infiniburn_end"),
					nbt.NewByteTag("has_raids", 1),
					nbt.NewByteTag("has_skylight", 0),
					nbt.NewStringTag("effects", "minecraft:the_end"),
					nbt.NewByteTag("ultrawarm", 0),
					nbt.NewByteTag("has_ceiling", 0),
					nbt.NewFloatTag("ambient_light", 0),
					nbt.NewIntTag("logical_height", 256),
					nbt.NewDoubleTag("coordinate_scale", 1),
					nbt.NewIntTag("fixed_time", 6000),
					nbt.NewByteTag("piglin_safe", 0),
					nbt.NewByteTag("respawn_anchor_works", 0),
					nbt.NewByteTag("bed_works", 0),
				}),
			})}, nbt.IDTagCompound),
	}),
	nbt.NewCompoundTag("minecraft:worldgen/biome", []nbt.Tag{
		nbt.NewStringTag("type", "minecraft:worldgen/biome"),
		nbt.NewListTag("value", []nbt.Tag{
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:ocean"),
				nbt.NewIntTag("id", 0),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("depth", -1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:plains"),
				nbt.NewIntTag("id", 1),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.05),
					nbt.NewDoubleTag("downfall", 0.4),
					nbt.NewStringTag("category", "plains"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
						nbt.NewIntTag("sky_color", 7.907327e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.125),
					nbt.NewDoubleTag("temperature", 0.8),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:desert"),
				nbt.NewIntTag("id", 2),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.125),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.05),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "desert"),
					nbt.NewStringTag("precipitation", "none"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:mountains"),
				nbt.NewIntTag("id", 3),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.2),
					nbt.NewDoubleTag("scale", 0.5),
					nbt.NewDoubleTag("downfall", 0.3),
					nbt.NewStringTag("category", "extreme_hills"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
						nbt.NewIntTag("sky_color", 8.233727e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewIntTag("depth", 1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 4),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.972607e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.7),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "forest"),
				}),
				nbt.NewStringTag("name", "minecraft:forest"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:taiga"),
				nbt.NewIntTag("id", 5),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.25),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.233983e+06),
					}),
					nbt.NewDoubleTag("depth", 0.2),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 6),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", -0.2),
					nbt.NewDoubleTag("temperature", 0.8),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.9),
					nbt.NewStringTag("category", "swamp"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 2.302743e+06),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 6.38858e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewStringTag("grass_color_modifier", "swamp"),
						nbt.NewIntTag("sky_color", 7.907327e+06),
						nbt.NewIntTag("foliage_color", 6.975545e+06),
					}),
				}),
				nbt.NewStringTag("name", "minecraft:swamp"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:river"),
				nbt.NewIntTag("id", 7),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "river"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", -0.5),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewIntTag("scale", 0),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:nether_wastes"),
				nbt.NewIntTag("id", 8),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "nether"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("additions_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.nether_wastes.additions"),
							nbt.NewDoubleTag("tick_chance", 0.0111),
						}),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 3.344392e+06),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.nether_wastes.mood"),
						}),
						nbt.NewCompoundTag("music", []nbt.Tag{
							nbt.NewIntTag("replace_current_music", 0),
							nbt.NewIntTag("max_delay", 24000),
							nbt.NewStringTag("sound", "minecraft:music.nether.nether_wastes"),
							nbt.NewIntTag("min_delay", 12000),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewStringTag("ambient_sound", "minecraft:ambient.nether_wastes.loop"),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:the_end"),
				nbt.NewIntTag("id", 9),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 0),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.0518688e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "the_end"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:frozen_ocean"),
				nbt.NewIntTag("id", 10),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("temperature_modifier", "frozen"),
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.364543e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 3.750089e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
					}),
					nbt.NewIntTag("depth", -1),
					nbt.NewIntTag("temperature", 0),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:frozen_river"),
				nbt.NewIntTag("id", 11),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("temperature", 0),
					nbt.NewIntTag("scale", 0),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "river"),
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.364543e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 3.750089e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", -0.5),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:snowy_tundra"),
				nbt.NewIntTag("id", 12),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.364543e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.125),
					nbt.NewIntTag("temperature", 0),
					nbt.NewDoubleTag("scale", 0.05),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "icy"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:snowy_mountains"),
				nbt.NewIntTag("id", 13),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "icy"),
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.364543e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewIntTag("temperature", 0),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:mushroom_fields"),
				nbt.NewIntTag("id", 14),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.9),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewIntTag("downfall", 1),
					nbt.NewStringTag("category", "mushroom"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:mushroom_field_shore"),
				nbt.NewIntTag("id", 15),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "mushroom"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
					}),
					nbt.NewIntTag("depth", 0),
					nbt.NewDoubleTag("temperature", 0.9),
					nbt.NewDoubleTag("scale", 0.025),
					nbt.NewIntTag("downfall", 1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:beach"),
				nbt.NewIntTag("id", 16),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.907327e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
					}),
					nbt.NewIntTag("depth", 0),
					nbt.NewDoubleTag("temperature", 0.8),
					nbt.NewDoubleTag("scale", 0.025),
					nbt.NewDoubleTag("downfall", 0.4),
					nbt.NewStringTag("category", "beach"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:desert_hills"),
				nbt.NewIntTag("id", 17),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "desert"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.45),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:wooded_hills"),
				nbt.NewIntTag("id", 18),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewDoubleTag("temperature", 0.7),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.972607e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:taiga_hills"),
				nbt.NewIntTag("id", 19),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.25),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
						nbt.NewIntTag("sky_color", 8.233983e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.45),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:mountain_edge"),
				nbt.NewIntTag("id", 20),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
						nbt.NewIntTag("sky_color", 8.233727e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.8),
					nbt.NewDoubleTag("temperature", 0.2),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.3),
					nbt.NewStringTag("category", "extreme_hills"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.95),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.9),
					nbt.NewStringTag("category", "jungle"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
						nbt.NewIntTag("sky_color", 7.842047e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
				}),
				nbt.NewStringTag("name", "minecraft:jungle"),
				nbt.NewIntTag("id", 21),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewDoubleTag("temperature", 0.95),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.9),
					nbt.NewStringTag("category", "jungle"),
				}),
				nbt.NewStringTag("name", "minecraft:jungle_hills"),
				nbt.NewIntTag("id", 22),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:jungle_edge"),
				nbt.NewIntTag("id", 23),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "jungle"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.95),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:deep_ocean"),
				nbt.NewIntTag("id", 24),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
					}),
					nbt.NewDoubleTag("depth", -1.8),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:stone_shore"),
				nbt.NewIntTag("id", 25),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.2),
					nbt.NewDoubleTag("scale", 0.8),
					nbt.NewDoubleTag("downfall", 0.3),
					nbt.NewStringTag("category", "none"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.233727e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:snowy_beach"),
				nbt.NewIntTag("id", 26),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.364543e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.020182e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
					}),
					nbt.NewIntTag("depth", 0),
					nbt.NewDoubleTag("temperature", 0.05),
					nbt.NewDoubleTag("scale", 0.025),
					nbt.NewDoubleTag("downfall", 0.3),
					nbt.NewStringTag("category", "beach"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:birch_forest"),
				nbt.NewIntTag("id", 27),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.037887e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.6),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.6),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:birch_forest_hills"),
				nbt.NewIntTag("id", 28),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.037887e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewDoubleTag("temperature", 0.6),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.6),
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:dark_forest"),
				nbt.NewIntTag("id", 29),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewStringTag("grass_color_modifier", "dark_forest"),
						nbt.NewIntTag("sky_color", 7.972607e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.7),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:snowy_taiga"),
				nbt.NewIntTag("id", 30),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.020182e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.625919e+06),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", -0.5),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.4),
					nbt.NewStringTag("category", "taiga"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:snowy_taiga_hills"),
				nbt.NewIntTag("id", 31),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.4),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.625919e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.020182e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewDoubleTag("temperature", -0.5),
					nbt.NewDoubleTag("scale", 0.3),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:giant_tree_taiga"),
				nbt.NewIntTag("id", 32),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.3),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
						nbt.NewIntTag("sky_color", 8.168447e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:giant_tree_taiga_hills"),
				nbt.NewIntTag("id", 33),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.168447e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewDoubleTag("temperature", 0.3),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.8),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:wooded_mountains"),
				nbt.NewIntTag("id", 34),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "extreme_hills"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.233727e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
					}),
					nbt.NewIntTag("depth", 1),
					nbt.NewDoubleTag("temperature", 0.2),
					nbt.NewDoubleTag("scale", 0.5),
					nbt.NewDoubleTag("downfall", 0.3),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 35),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "savanna"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.711487e+06),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 0.125),
					nbt.NewDoubleTag("temperature", 1.2),
					nbt.NewDoubleTag("scale", 0.05),
				}),
				nbt.NewStringTag("name", "minecraft:savanna"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:savanna_plateau"),
				nbt.NewIntTag("id", 36),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.025),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "savanna"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.776511e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 1.5),
					nbt.NewIntTag("temperature", 1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:badlands"),
				nbt.NewIntTag("id", 37),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "mesa"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("foliage_color", 1.0387789e+07),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("grass_color", 9.470285e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewIntTag("downfall", 0),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.025),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "mesa"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("grass_color", 9.470285e+06),
						nbt.NewIntTag("foliage_color", 1.0387789e+07),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 1.5),
					nbt.NewIntTag("temperature", 2),
				}),
				nbt.NewStringTag("name", "minecraft:wooded_badlands_plateau"),
				nbt.NewIntTag("id", 38),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:badlands_plateau"),
				nbt.NewIntTag("id", 39),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 1.5),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.025),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "mesa"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("grass_color", 9.470285e+06),
						nbt.NewIntTag("foliage_color", 1.0387789e+07),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "the_end"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 0),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.0518688e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.5),
				}),
				nbt.NewStringTag("name", "minecraft:small_end_islands"),
				nbt.NewIntTag("id", 40),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "the_end"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 0),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.0518688e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.2),
				}),
				nbt.NewStringTag("name", "minecraft:end_midlands"),
				nbt.NewIntTag("id", 41),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 42),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 0),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.0518688e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "the_end"),
					nbt.NewStringTag("precipitation", "none"),
				}),
				nbt.NewStringTag("name", "minecraft:end_highlands"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:end_barrens"),
				nbt.NewIntTag("id", 43),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 0),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.0518688e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "the_end"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.445678e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 270131),
					}),
					nbt.NewIntTag("depth", -1),
				}),
				nbt.NewStringTag("name", "minecraft:warm_ocean"),
				nbt.NewIntTag("id", 44),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:lukewarm_ocean"),
				nbt.NewIntTag("id", 45),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 267827),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.566514e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
					}),
					nbt.NewIntTag("depth", -1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:cold_ocean"),
				nbt.NewIntTag("id", 46),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.020182e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewIntTag("depth", -1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:deep_warm_ocean"),
				nbt.NewIntTag("id", 47),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.445678e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 270131),
					}),
					nbt.NewDoubleTag("depth", -1.8),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 48),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 267827),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.566514e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.103167e+06),
					}),
					nbt.NewDoubleTag("depth", -1.8),
				}),
				nbt.NewStringTag("name", "minecraft:deep_lukewarm_ocean"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 49),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.020182e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
						nbt.NewIntTag("sky_color", 8.103167e+06),
					}),
					nbt.NewDoubleTag("depth", -1.8),
					nbt.NewDoubleTag("temperature", 0.5),
				}),
				nbt.NewStringTag("name", "minecraft:deep_cold_ocean"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 3.750089e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", -1.8),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.1),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "ocean"),
					nbt.NewStringTag("temperature_modifier", "frozen"),
				}),
				nbt.NewStringTag("name", "minecraft:deep_frozen_ocean"),
				nbt.NewIntTag("id", 50),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:the_void"),
				nbt.NewIntTag("id", 127),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "none"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
						nbt.NewIntTag("sky_color", 8.103167e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.5),
					nbt.NewDoubleTag("scale", 0.2),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:sunflower_plains"),
				nbt.NewIntTag("id", 129),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.125),
					nbt.NewDoubleTag("temperature", 0.8),
					nbt.NewDoubleTag("scale", 0.05),
					nbt.NewDoubleTag("downfall", 0.4),
					nbt.NewStringTag("category", "plains"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.907327e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:desert_lakes"),
				nbt.NewIntTag("id", 130),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.225),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.25),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "desert"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("depth", 1),
					nbt.NewDoubleTag("temperature", 0.2),
					nbt.NewDoubleTag("scale", 0.5),
					nbt.NewDoubleTag("downfall", 0.3),
					nbt.NewStringTag("category", "extreme_hills"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.233727e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
				}),
				nbt.NewStringTag("name", "minecraft:gravelly_mountains"),
				nbt.NewIntTag("id", 131),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.972607e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.7),
					nbt.NewDoubleTag("scale", 0.4),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "forest"),
				}),
				nbt.NewStringTag("name", "minecraft:flower_forest"),
				nbt.NewIntTag("id", 132),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.233983e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.3),
					nbt.NewDoubleTag("temperature", 0.25),
					nbt.NewDoubleTag("scale", 0.4),
					nbt.NewDoubleTag("downfall", 0.8),
				}),
				nbt.NewStringTag("name", "minecraft:taiga_mountains"),
				nbt.NewIntTag("id", 133),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:swamp_hills"),
				nbt.NewIntTag("id", 134),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "swamp"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 6.38858e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
						nbt.NewStringTag("grass_color_modifier", "swamp"),
						nbt.NewIntTag("sky_color", 7.907327e+06),
						nbt.NewIntTag("foliage_color", 6.975545e+06),
						nbt.NewIntTag("water_fog_color", 2.302743e+06),
					}),
					nbt.NewDoubleTag("depth", -0.1),
					nbt.NewDoubleTag("temperature", 0.8),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewDoubleTag("downfall", 0.9),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.425),
					nbt.NewIntTag("temperature", 0),
					nbt.NewDoubleTag("scale", 0.45000002),
					nbt.NewDoubleTag("downfall", 0.5),
					nbt.NewStringTag("category", "icy"),
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 8.364543e+06),
					}),
				}),
				nbt.NewStringTag("name", "minecraft:ice_spikes"),
				nbt.NewIntTag("id", 140),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:modified_jungle"),
				nbt.NewIntTag("id", 149),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.95),
					nbt.NewDoubleTag("scale", 0.4),
					nbt.NewDoubleTag("downfall", 0.9),
					nbt.NewStringTag("category", "jungle"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:modified_jungle_edge"),
				nbt.NewIntTag("id", 151),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 0.4),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "jungle"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
						nbt.NewIntTag("sky_color", 7.842047e+06),
					}),
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.95),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:tall_birch_forest"),
				nbt.NewIntTag("id", 155),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
						nbt.NewIntTag("sky_color", 8.037887e+06),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.6),
					nbt.NewDoubleTag("scale", 0.4),
					nbt.NewDoubleTag("downfall", 0.6),
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:tall_birch_hills"),
				nbt.NewIntTag("id", 156),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.55),
					nbt.NewDoubleTag("temperature", 0.6),
					nbt.NewDoubleTag("scale", 0.5),
					nbt.NewDoubleTag("downfall", 0.6),
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.037887e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:dark_forest_hills"),
				nbt.NewIntTag("id", 157),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.7),
					nbt.NewDoubleTag("scale", 0.4),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "forest"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewStringTag("grass_color_modifier", "dark_forest"),
						nbt.NewIntTag("sky_color", 7.972607e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
					}),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:snowy_taiga_mountains"),
				nbt.NewIntTag("id", 158),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.4),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "snow"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.625919e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.020182e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.3),
					nbt.NewDoubleTag("temperature", -0.5),
					nbt.NewDoubleTag("scale", 0.4),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:giant_spruce_taiga"),
				nbt.NewIntTag("id", 160),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 8.233983e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.2),
					nbt.NewDoubleTag("temperature", 0.25),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 161),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("temperature", 0.25),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.8),
					nbt.NewStringTag("category", "taiga"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
						}),
						nbt.NewIntTag("sky_color", 8.233983e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
					}),
					nbt.NewDoubleTag("depth", 0.2),
				}),
				nbt.NewStringTag("name", "minecraft:giant_spruce_taiga_hills"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:modified_gravelly_mountains"),
				nbt.NewIntTag("id", 162),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.3),
					nbt.NewStringTag("category", "extreme_hills"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
						}),
						nbt.NewIntTag("sky_color", 8.233727e+06),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewIntTag("depth", 1),
					nbt.NewDoubleTag("temperature", 0.2),
					nbt.NewDoubleTag("scale", 0.5),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:shattered_savanna"),
				nbt.NewIntTag("id", 163),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.776767e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.3625),
					nbt.NewDoubleTag("temperature", 1.1),
					nbt.NewDoubleTag("scale", 1.225),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "savanna"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:shattered_savanna_plateau"),
				nbt.NewIntTag("id", 164),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("scale", 1.2125001),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "savanna"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.776511e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
					}),
					nbt.NewDoubleTag("depth", 1.05),
					nbt.NewIntTag("temperature", 1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 165),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("category", "mesa"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("grass_color", 9.470285e+06),
						nbt.NewIntTag("foliage_color", 1.0387789e+07),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewIntTag("downfall", 0),
				}),
				nbt.NewStringTag("name", "minecraft:eroded_badlands"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:modified_wooded_badlands_plateau"),
				nbt.NewIntTag("id", 166),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "mesa"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("foliage_color", 1.0387789e+07),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("grass_color", 9.470285e+06),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.3),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:modified_badlands_plateau"),
				nbt.NewIntTag("id", 167),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("grass_color", 9.470285e+06),
						nbt.NewIntTag("foliage_color", 1.0387789e+07),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.3),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "mesa"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:bamboo_jungle"),
				nbt.NewIntTag("id", 168),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewDoubleTag("temperature", 0.95),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewDoubleTag("downfall", 0.9),
					nbt.NewStringTag("category", "jungle"),
					nbt.NewStringTag("precipitation", "rain"),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:bamboo_jungle_hills"),
				nbt.NewIntTag("id", 169),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("downfall", 0.9),
					nbt.NewStringTag("category", "jungle"),
					nbt.NewStringTag("precipitation", "rain"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.842047e+06),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.2638463e+07),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.cave"),
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
						}),
					}),
					nbt.NewDoubleTag("depth", 0.45),
					nbt.NewDoubleTag("temperature", 0.95),
					nbt.NewDoubleTag("scale", 0.3),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewIntTag("id", 170),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "nether"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewCompoundTag("additions_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.soul_sand_valley.additions"),
							nbt.NewDoubleTag("tick_chance", 0.0111),
						}),
						nbt.NewCompoundTag("particle", []nbt.Tag{
							nbt.NewDoubleTag("probability", 0.00625),
							nbt.NewCompoundTag("options", []nbt.Tag{
								nbt.NewStringTag("type", "minecraft:ash"),
							}),
						}),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("block_search_extent", 8),
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.soul_sand_valley.mood"),
						}),
						nbt.NewCompoundTag("music", []nbt.Tag{
							nbt.NewIntTag("replace_current_music", 0),
							nbt.NewIntTag("max_delay", 24000),
							nbt.NewStringTag("sound", "minecraft:music.nether.soul_sand_valley"),
							nbt.NewIntTag("min_delay", 12000),
						}),
						nbt.NewStringTag("ambient_sound", "minecraft:ambient.soul_sand_valley.loop"),
						nbt.NewIntTag("fog_color", 1.787717e+06),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
				}),
				nbt.NewStringTag("name", "minecraft:soul_sand_valley"),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:crimson_forest"),
				nbt.NewIntTag("id", 171),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "nether"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewCompoundTag("particle", []nbt.Tag{
							nbt.NewDoubleTag("probability", 0.025),
							nbt.NewCompoundTag("options", []nbt.Tag{
								nbt.NewStringTag("type", "minecraft:crimson_spore"),
							}),
						}),
						nbt.NewIntTag("fog_color", 3.343107e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.crimson_forest.mood"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("music", []nbt.Tag{
							nbt.NewIntTag("replace_current_music", 0),
							nbt.NewIntTag("max_delay", 24000),
							nbt.NewStringTag("sound", "minecraft:music.nether.crimson_forest"),
							nbt.NewIntTag("min_delay", 12000),
						}),
						nbt.NewStringTag("ambient_sound", "minecraft:ambient.crimson_forest.loop"),
						nbt.NewCompoundTag("additions_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.crimson_forest.additions"),
							nbt.NewDoubleTag("tick_chance", 0.0111),
						}),
						nbt.NewIntTag("water_fog_color", 329011),
					}),
					nbt.NewDoubleTag("depth", 0.1),
				}),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewStringTag("ambient_sound", "minecraft:ambient.warped_forest.loop"),
						nbt.NewCompoundTag("additions_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.warped_forest.additions"),
							nbt.NewDoubleTag("tick_chance", 0.0111),
						}),
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.warped_forest.mood"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewCompoundTag("music", []nbt.Tag{
							nbt.NewIntTag("replace_current_music", 0),
							nbt.NewIntTag("max_delay", 24000),
							nbt.NewStringTag("sound", "minecraft:music.nether.warped_forest"),
							nbt.NewIntTag("min_delay", 12000),
						}),
						nbt.NewCompoundTag("particle", []nbt.Tag{
							nbt.NewDoubleTag("probability", 0.01428),
							nbt.NewCompoundTag("options", []nbt.Tag{
								nbt.NewStringTag("type", "minecraft:warped_spore"),
							}),
						}),
						nbt.NewIntTag("water_fog_color", 329011),
						nbt.NewIntTag("fog_color", 1.705242e+06),
					}),
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "nether"),
				}),
				nbt.NewStringTag("name", "minecraft:warped_forest"),
				nbt.NewIntTag("id", 172),
			}),
			nbt.NewCompoundTag("", []nbt.Tag{
				nbt.NewStringTag("name", "minecraft:basalt_deltas"),
				nbt.NewIntTag("id", 173),
				nbt.NewCompoundTag("element", []nbt.Tag{
					nbt.NewDoubleTag("depth", 0.1),
					nbt.NewIntTag("temperature", 2),
					nbt.NewDoubleTag("scale", 0.2),
					nbt.NewIntTag("downfall", 0),
					nbt.NewStringTag("category", "nether"),
					nbt.NewStringTag("precipitation", "none"),
					nbt.NewCompoundTag("effects", []nbt.Tag{
						nbt.NewIntTag("water_color", 4.159204e+06),
						nbt.NewCompoundTag("music", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:music.nether.basalt_deltas"),
							nbt.NewIntTag("min_delay", 12000),
							nbt.NewIntTag("replace_current_music", 0),
							nbt.NewIntTag("max_delay", 24000),
						}),
						nbt.NewStringTag("ambient_sound", "minecraft:ambient.basalt_deltas.loop"),
						nbt.NewIntTag("water_fog_color", 4.341314e+06),
						nbt.NewIntTag("fog_color", 6.840176e+06),
						nbt.NewCompoundTag("mood_sound", []nbt.Tag{
							nbt.NewIntTag("tick_delay", 6000),
							nbt.NewIntTag("offset", 2),
							nbt.NewStringTag("sound", "minecraft:ambient.basalt_deltas.mood"),
							nbt.NewIntTag("block_search_extent", 8),
						}),
						nbt.NewIntTag("sky_color", 7.254527e+06),
						nbt.NewCompoundTag("additions_sound", []nbt.Tag{
							nbt.NewStringTag("sound", "minecraft:ambient.basalt_deltas.additions"),
							nbt.NewDoubleTag("tick_chance", 0.0111),
						}),
						nbt.NewCompoundTag("particle", []nbt.Tag{
							nbt.NewDoubleTag("probability", 0.118093334),
							nbt.NewCompoundTag("options", []nbt.Tag{
								nbt.NewStringTag("type", "minecraft:white_ash"),
							}),
						}),
					}),
				}),
			})}, nbt.IDTagCompound),
	}),
})
