// Code generated by "stringer -trimprefix=Gamemode -type=Gamemode"; DO NOT EDIT.

package game

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[GamemodeSurvival-0]
	_ = x[GamemodeCreative-1]
	_ = x[GamemodeAdventure-2]
	_ = x[GamemodeSpectator-3]
}

const _Gamemode_name = "SurvivalCreativeAdventureSpectator"

var _Gamemode_index = [...]uint8{0, 8, 16, 25, 34}

func (i Gamemode) String() string {
	if i < 0 || i >= Gamemode(len(_Gamemode_index)-1) {
		return "Gamemode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Gamemode_name[_Gamemode_index[i]:_Gamemode_index[i+1]]
}
