// Code generated by "stringer -linecomment -trimprefix=Phase -type=Phase"; DO NOT EDIT.

package packet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PhaseInvalid-0]
	_ = x[PhaseHandshaking-1]
	_ = x[PhaseStatus-2]
	_ = x[PhaseLogin-3]
	_ = x[PhasePlay-4]
}

const _Phase_name = "InvalidHandshakingStatusLoginPlay"

var _Phase_index = [...]uint8{0, 7, 18, 24, 29, 33}

func (i Phase) String() string {
	if i >= Phase(len(_Phase_index)-1) {
		return "Phase(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Phase_name[_Phase_index[i]:_Phase_index[i+1]]
}
