// Code generated by "stringer -linecomment -type=State"; DO NOT EDIT.

package packet

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StateInvalid-0]
	_ = x[StateHandshaking-1]
	_ = x[StateStatus-2]
	_ = x[StateLogin-3]
	_ = x[StatePlay-4]
}

const _State_name = "InvalidHandshakingStatusLoginPlay"

var _State_index = [...]uint8{0, 7, 18, 24, 29, 33}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
