// Code generated by "stringer -linecomment -type=CatType"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CatTypeTabby-0]
	_ = x[CatTypeTuxedo-1]
	_ = x[CatTypeRed-2]
	_ = x[CatTypeSiamese-3]
	_ = x[CatTypeBritishShorthair-4]
	_ = x[CatTypeCalico-5]
	_ = x[CatTypePersian-6]
	_ = x[CatTypeRagdoll-7]
	_ = x[CatTypeWhite-8]
	_ = x[CatTypeJellie-9]
	_ = x[CatTypeBlack-10]
}

const _CatType_name = "TabbyTuxedoRedSiameseBritish ShorthairCalicoPersianRagdollWhiteJellieBlack"

var _CatType_index = [...]uint8{0, 5, 11, 14, 21, 38, 44, 51, 58, 63, 69, 74}

func (i CatType) String() string {
	if i < 0 || i >= CatType(len(_CatType_index)-1) {
		return "CatType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CatType_name[_CatType_index[i]:_CatType_index[i+1]]
}
