// Code generated by "stringer -linecomment -trimprefix=Color -type=Color"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ColorWhite-0]
	_ = x[ColorOrange-1]
	_ = x[ColorMagenta-2]
	_ = x[ColorLightBlue-3]
	_ = x[ColorYellow-4]
	_ = x[ColorLime-5]
	_ = x[ColorPink-6]
	_ = x[ColorGray-7]
	_ = x[ColorLightGray-8]
	_ = x[ColorCyan-9]
	_ = x[ColorPurple-10]
	_ = x[ColorBlue-11]
	_ = x[ColorBrown-12]
	_ = x[ColorGreen-13]
	_ = x[ColorRed-14]
	_ = x[ColorBlack-15]
}

const _Color_name = "WhiteOrangeMagentaLightBlueYellowLimePinkGrayLightGrayCyanPurpleBlueBrownGreenRedBlack"

var _Color_index = [...]uint8{0, 5, 11, 18, 27, 33, 37, 41, 45, 54, 58, 64, 68, 73, 78, 81, 86}

func (i Color) String() string {
	if i >= Color(len(_Color_index)-1) {
		return "Color(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Color_name[_Color_index[i]:_Color_index[i+1]]
}
