// Code generated by "stringer -linecomment -output effect_id_string.go -type=EffectID"; DO NOT EDIT.

package entity

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EffectIDInvalid-0]
	_ = x[EffectIDSpeed-1]
	_ = x[EffectIDSlowness-2]
	_ = x[EffectIDHaste-3]
	_ = x[EffectIDMiningFatigue-4]
	_ = x[EffectIDStrength-5]
	_ = x[EffectIDInstantHealth-6]
	_ = x[EffectIDInstantDamage-7]
	_ = x[EffectIDJumpBoost-8]
	_ = x[EffectIDNausea-9]
	_ = x[EffectIDRegeneration-10]
	_ = x[EffectIDResistance-11]
	_ = x[EffectIDFireResistance-12]
	_ = x[EffectIDWaterBreathing-13]
	_ = x[EffectIDInvisibility-14]
	_ = x[EffectIDBlindness-15]
	_ = x[EffectIDNightVision-16]
	_ = x[EffectIDHunger-17]
	_ = x[EffectIDWeakness-18]
	_ = x[EffectIDPoison-19]
	_ = x[EffectIDWither-20]
	_ = x[EffectIDHealthBoost-21]
	_ = x[EffectIDAbsorption-22]
	_ = x[EffectIDSaturation-23]
	_ = x[EffectIDGlowing-24]
	_ = x[EffectIDLevitation-25]
	_ = x[EffectIDLuck-26]
	_ = x[EffectIDBadLuck-27]
	_ = x[EffectIDSlowFalling-28]
	_ = x[EffectIDConduitPower-29]
	_ = x[EffectIDDolphinsGrace-30]
	_ = x[EffectIDBadOmen-31]
	_ = x[EffectIDHeroOfTheVillage-32]
}

const _EffectID_name = "invalidspeedslownesshastemining_fatiguestrengthinstant_healthinstant_damagejump_boostnausearegenerationresistancefire_resistancewater_breathinginvisibilityblindnessnight_visionhungerweaknesspoisonwitherhealth_boostabsorptionsaturationglowinglevitationluckunluckslow_fallingconduit_powerdolphins_gracebad_omenhero_of_the_village"

var _EffectID_index = [...]uint16{0, 7, 12, 20, 25, 39, 47, 61, 75, 85, 91, 103, 113, 128, 143, 155, 164, 176, 182, 190, 196, 202, 214, 224, 234, 241, 251, 255, 261, 273, 286, 300, 308, 327}

func (i EffectID) String() string {
	if i >= EffectID(len(_EffectID_index)-1) {
		return "EffectID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EffectID_name[_EffectID_index[i]:_EffectID_index[i+1]]
}
