// Code generated by "stringer -linecomment -type=CompressionType"; DO NOT EDIT.

package world

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CompressionGZip-1]
	_ = x[CompressionZlib-2]
	_ = x[CompressionUncompressed-3]
}

const _CompressionType_name = "GZipZlibuncompressed"

var _CompressionType_index = [...]uint8{0, 4, 8, 20}

func (i CompressionType) String() string {
	i -= 1
	if i >= CompressionType(len(_CompressionType_index)-1) {
		return "CompressionType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CompressionType_name[_CompressionType_index[i]:_CompressionType_index[i+1]]
}
